env: antmaze-large-play-v2
seed: 1
vae_model_path: models/vae_trained_models/vae_model_antmaze_large-play.pt
pretrain_model: models/offline_trained_models/antmaze_large-play
lambd: 0.025
lambd_cool: true
actor_lr: 0.0001
actor_dropout: 0.0
antmaze_no_normalize: true
discount: 0.995
eval_episodes: 100
eval_freq: 50000
work_dir: train_finetune
