env: antmaze-umaze-v2
vae_model_path: models/vae_trained_models/vae_model_antmaze_umaze.pt
lambd: 0.25
actor_lr: 0.0001
actor_dropout: 0.0
actor_init_w: 0.001
critic_init_w: 0.003
antmaze_no_normalize: true
eval_episodes: 100
eval_freq: 50000
work_dir: train_offline
